version: 1

formatters:
    simple:
        format: "%(name)s - %(lineno)d -  %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple

loggers:
    __main__:
        level: DEBUG
        handlers: [console]
        propagate: yes
